### ISSUE TITLE
Automatic picture measuring python script is crashing on launch 0.0.7

### ISSUE THREAD

**Issue by JohnSpruijt2** [JohnSpruijt2/FishFarm#1]
Traceback (most recent call last):
  File "C:\Users\johns\OneDrive\School\jaar 3\FishFarm\python\measure_object_size.py", line 93, in <module>
    measure()
  File "C:\Users\johns\OneDrive\School\jaar 3\FishFarm\python\measure_object_size.py", line 34, in measure
    corners, _, _ = cv2.aruco.detectMarkers(imgage, aruco_dict, parameters=parameters)
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv_contrib\modules\aruco\src\aruco.cpp:1031: error: (-215:Assertion failed) !_image.empty() in function 'cv::aruco::detectMarkers'

**Comment by JohnSpruijt2** [comment]
was reading out the wrong entry in an array had to look one past the one that it was looking at
